# Site settings
title: King Philanthropies
email: contact@kingphilanthropies.org
description: >
  Welcome to the home of King Philanthropies.
baseurl: ""
url: "http://www.kingphilanthropies.org" # the base hostname & protocol for your site
image_path: '/assets/img'

# Build settings
markdown: kramdown
permalink: /:title
exclude: ['_sass', '_src', '_grunt', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'Gemfile']

# Enabling gems
gems: [jekyll-contentful]

defaults:
  -
    scope:
      type: "posts"
    values: 
      layout: "post"
      permalink: /blog/:title
  -
    scope:
      path: "/category"
    values:
      permalink: /blog/category/:title
      layout: "category"


contentful:
  preview: No 
  production_access_token: 3d88520854d1da679fd8e8ccacba8de2e3fb4c52d961f048ea6eb4920595ef5a
  preview_access_token: ff241d9d39d3af4210090005a7b55d468faff83eaa6684a2d2941c61541b9b43
  space: 0cp1epmalnde
  content_types:
   - "initiatives"
   - "staffMember"
   - "founder"
   - "letter"
  spaces:
    - proddata: # Jekyll _data folder identifier - Required
        space: 0cp1epmalnde        # Required
        access_token: 3d88520854d1da679fd8e8ccacba8de2e3fb4c52d961f048ea6eb4920595ef5a # Required
        cda_query:                 # Optional
          include: 2
          limit: 100
        content_types:             # Optional
          cat: boardMember
          cat: initiatives
          cat: letter
          cat: newsPost
          cat: staffMember
          cat: founder
          cat: letter
          cat: pages
