---
staff:
- sys:
    id: 75yDcrmAb68owGOeaaC2Ui
  name: Staff 1
  title: Lead Dev
  bio: bio here
- sys:
    id: 7dwcU7irS0Q0G44wGyAoaE
  name: Staff 3
  title: Director of comm.
- sys:
    id: 6lWDrknPhK0qiEqukkS4oK
  name: Staff 2
  title: Dev
  bio: Bio
initiatives:
- sys:
    id: 7udm6iSqOc4ecywi2yq6kW
  name: Thrivefoundation
  picture:
    title: King
    url: //images.contentful.com/q8yrepkn2bph/1MPXOSluHKcAyWMSKSa0uO/93e276265041e5de3ba9b2698d9a06fc/premium-services_318-31765.jpg
  blurb: this is the blurb
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. '
